service: telegram-msg-count-bot
app: myapp
org: sasuke40
provider:
  name: aws
  runtime: nodejs12.x
functions:
  bot:
    handler: handler.main
    events:
      - http:
          path: /bot
          method: post
          cors: true
    environment:
      BOT_TOKEN: "1155404961:AAF7Ad49UMEAesGSjRnr_LEXKzPoFdTehBY"
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TelegramMsgCount
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
plugins:
  - serverless-dynamodb-local
custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
